# Generated by Django 3.1 on 2020-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
