# Generated by Django 3.1 on 2020-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200819_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
